#!/usr/bin/env bash

set -e

SOURCE="${BASH_SOURCE[0]}"
if [ -h "$SOURCE" ]; then
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
fi
DIR="$( cd "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
DEFAULT_CONTAINER_NAME=`cat $DIR/CONTAINER_NAME`
CONTAINER=${1:-$DEFAULT_CONTAINER_NAME}

docker stop $CONTAINER